User, Repository, Provider 모델 추가
AlgoSolved/AlgoSolved pull request #11
Opened 2023-11-25 08:40 UTC by rha6780

## 작업 내용
- user, repository, provider 모델 추가

## 이슈
- 작업을 하게 된 배경을 설명합니다.
- 기획자와의 의사 결정 내용 등 이 코드가 만들어지게 된 배경 있다면 모조리 적습니다.

## 체크 리스트
- Merge/배포 후에 체크해야할 사항이 있으면 적어주세요.

2023-11-27 15:07 UTC, youngjun0627 commented on backend/src/main/java/com/example/backend/model/BaseTimeEntity.java
> +package com.example.backend.model;
요 파일만 별도로 빼서 PR 만들어주실 수 있을까요?

2023-11-27 15:13 UTC, youngjun0627 approved these changes
수고하셨습니다!

2023-11-27 15:13 UTC, youngjun0627 commented on backend/src/main/java/com/example/backend/model/User.java
> +@SQLDelete(sql="UPDATE users SET deleted_at = CURRENT_TIMESTAMP WHERE id = ?")
soft delete 적용한 이유 알 수 있을까요?

2023-11-27 15:13 UTC, youngjun0627 commented on backend/src/main/java/com/example/backend/model/User.java
> +    private String role;
role 보다는 roles 로 배열로 관리하는거 어떠신가요? 각 역할마다 권한을 부여해서 관리하면 좋을 거 같아서요

2023-11-27 15:13 UTC, youngjun0627 commented on backend/src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create-drop
create-drop 보다 validate 어떠신가요?
ref: https://pravusid.kr/java/2018/10/10/spring-database-initialization.html

2023-11-27 20:09 UTC, mmmtobezip commented on backend/src/main/java/com/example/backend/model/User.java
> +    private Repository repository;
혼동이 와서 질문드립니다 🥲
현재 테이블 관계는 양쪽 테이블에 각각의 외래키를 추가한 1:1 양방향 같은데요, 한명의 사용자는 여러 개의 레포지토리를 가질 수 있는 1:N 관계는 아닐까요..?

2023-11-28 02:08 UTC, youngjun0627 reviewed
추가로 model 이라는 폴더보다 domain 이라는 이름이 보편적으로 많이 사용되는거 같아요

ref: https://velog.io/@haron/Spring-Project-Structure

2023-11-28 11:27 UTC, rha6780 commented on backend/src/main/java/com/example/backend/model/BaseTimeEntity.java
> +package com.example.backend.model;
오 넵넵

2023-11-28 11:37 UTC, rha6780 commented on backend/src/main/java/com/example/backend/model/User.java
> +    private String role;
오 좋은 의견 감사합니다! 별도의 Enum 작성해서 관리해볼까요...? role에 뭘넣을지 고민이 되긴 하는데... admin, customer? 우선 임의로 추가하겠습니다.

2023-11-28 11:37 UTC, rha6780 commented on backend/src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create-drop
수정하겠습니다

2023-11-28 11:46 UTC, rha6780 commented on backend/src/main/java/com/example/backend/model/User.java
> +    private Repository repository;
> @XToOne(@OnetoOne, @manytoone) 연관 관계 일땐 default가 FetchType.EAGER로 동작하는 하기에 의도하지 않은 쿼리가 나가는 것을 방지하여 FetchType을 LAZY로 설정하는 것을 추천하여 적어주는 것도 좋다고 생각하는데, 이 부분에 대해 어떻게 생각하시나요?!

앗 지연로딩으로 수정해두겠습니다. 제 생각에도 수정하는게 좋다고 생각합니다.

2023-11-28 11:48 UTC, rha6780 commented on backend/src/main/java/com/example/backend/model/User.java
> +    private Repository repository;
> 혼동이 와서 질문드립니다 🥲 현재 테이블 관계는 양쪽 테이블에 각각의 외래키를 추가한 1:1 양방향 같은데요, 한명의 사용자는 여러 개의 레포지토리를 가질 수 있는 1:N 관계는 아닐까요..?

음... 이건 서비스 스펙에 따라 달라질 것 같은데요 제가 생각한 바로는 알고리즘 문제를 올린 레포지토리 1개만 저희 서비스와 연동 시키는 걸로 이해하고 있어서 OneToOne으로 작성하였습니다.

2023-11-28 13:49 UTC, youngjun0627 commented on backend/src/main/java/com/example/backend/model/User.java
> +    private String role;
일단 간단하게 admin 만 넣어보죠!

2023-11-28 15:36 UTC, youngjun0627 requested changes
flyway 적용하였으니 테이블 생성까지 부탁드립니다!
ref: https://github.com/AlgoSolved/AlgoSolved/pull/14


서버를 실행했을 때 해당 모델에 대응하는 테이블이 없다고 오류가 떠서 서버가 죽네요...

2023-11-29 06:31 UTC, youngjun0627 commented on backend/src/main/java/com/example/backend/domain/User.java
> +public class User extends BaseTimeEntity {
github 소셜로그인을 지원한다면 아마 별도의 authorization 토큰값을 저장하는 것도 필요하겠네요.
일단 요렇게만 만들고 본격적으로 github 소셜로그인 지원 기능 추가할 때 만들어보죠!

2023-11-29 12:33 UTC, rha6780 commented on backend/src/main/java/com/example/backend/domain/User.java
> +public class User extends BaseTimeEntity {
오 넵넵 좋습니다!

2023-11-29 16:34 UTC, rha6780 commented
> flyway 적용하였으니 테이블 생성까지 부탁드립니다! ref: #14
> 
> 서버를 실행했을 때 해당 모델에 대응하는 테이블이 없다고 오류가 떠서 서버가 죽네요...

우선 앞선 PR 이 V2까지 있어서 V3로 적었고(로컬에서 테스트할 때 V1으로 바꿔야할 것 같아요) 각각 아래와 같이 적용되도록 수정하였습니다.
<img width="650" alt="Screenshot 2023-11-30 at 1 14 24 AM" src="https://github.com/AlgoSolved/AlgoSolved/assets/47859845/0481f65b-2969-4e19-819d-2f8d68a91cbf">

<img width="650" alt="Screenshot 2023-11-30 at 1 14 05 AM" src="https://github.com/AlgoSolved/AlgoSolved/assets/47859845/93720cd9-0860-4202-b985-3f4d677fa198">

<img width="650" alt="Screenshot 2023-11-30 at 1 14 44 AM" src="https://github.com/AlgoSolved/AlgoSolved/assets/47859845/2a8be412-3c07-4594-b717-5ff825a73b5c">

2023-11-30 00:36 UTC, youngjun0627 reviewed
수고하셨습니다

2023-11-30 00:36 UTC, youngjun0627 commented on backend/src/main/java/com/example/backend/common/converters/RoleTypeListConverter.java
> +public class RoleTypeListConverter implements AttributeConverter<List<RoleType>, String> {
컨버터는 왜 추가하신건가요?

2023-11-30 00:36 UTC, youngjun0627 commented on backend/src/main/resources/db/migration/V3__user_repository_provider.sql
> +    id BIGINT PRIMARY KEY,
혹시 데이터 생성해보셨나요? 저는 bigint 로 id 생성했다가 JPA 에서 자동으로 id 가 생성안되더라구요. 찾아보니 JPA 에서 자동으로 생성해주려면 DB 에 해당 id 에 관한 sequence 도 생성해줘야하는거 같아서 그냥 serial 로 선언했습니다

2023-11-30 08:07 UTC, mmmtobezip commented on backend/src/main/java/com/example/backend/domain/Repository.java
> +}
Repository라는 엔터티 이름이 추후 JPA 사용시 인터페이스 이름에 주로 포함되어 있으니 UserRepository와 같이 바꾸는건 어떨까요?(+테이블명)

2023-11-30 08:17 UTC, youngjun0627 commented on backend/src/main/java/com/example/backend/domain/Repository.java
> +}
GithubRepository 라고 해도 좋을거 같아요

2023-11-30 11:15 UTC, rha6780 commented on backend/src/main/java/com/example/backend/common/converters/RoleTypeListConverter.java
> +public class RoleTypeListConverter implements AttributeConverter<List<RoleType>, String> {
enum 을 List로 넣어줄때, 별도로 객체를 만들거나 여러방식이 있었는데, converter가 제일 코드가 적은거 같아서 작성하였습니다..!

2023-11-30 11:15 UTC, rha6780 commented on backend/src/main/resources/db/migration/V3__user_repository_provider.sql
> +    id BIGINT PRIMARY KEY,
아하 아직 데이터는 생성을 안 해봤는데 테스트 해봐야 겠네요...! 👍

2023-11-30 11:15 UTC, rha6780 commented on backend/src/main/java/com/example/backend/domain/Repository.java
> +}
GithubRepository 로 적용하겠습니다.

2023-11-30 13:12 UTC, youngjun0627 approved these changes
수고하셨습니다!

2023-11-30 13:15 UTC, merged