alb 추가 및 Ec2 연결
AlgoSolved/AlgoSolved pull request #73
Opened 2024-05-13 16:35 UTC by rha6780

## 작업 내용
- ALB와 타겟그룹을 추가하고, 관련하여 헬스체크를 설정합니다.
- 관련된 autoScaling Atachment와 리스너를 추가합니다. HTTP 로 들어온 요청에 대해서 HTTPS 로 리다이렉트하도록 하였습니다.
- 헬스체크의 경우, 타겟이 설정 된 이후 최소 (healthy_threshold)2* interval(30초) = 60초 가 걸립니다.

| 리소스    | 옵션 이름 | 설명 |
| -------- | ------- |  ------- |
| aws_lb | load_balancer_type    |  로드벨런서의 타입으로 'application', 'network' 중 선택 가능(ALB, NLB) |
|    | idle_timeout   |  연결 유휴 시간(서버와 커넥션 유지 시간) Default 60초 ([참고링크](https://reaperes.medium.com/aws-alb-%EC%9D%98-idle-timeout-%EC%97%90-%EA%B4%80%ED%95%98%EC%97%AC-7addb8bfb886))  |
|    | ip_address_type   |  IP 주소 타입 (ipv4, dualstack) |
| aws_lb_target_group  | deregistration_delay    |  등록 취소 대기 시간, 타겟 그룹에서 드레이닝 -> 사용중지 로 변경될때까지 로드밸런싱을 대기하는 시간 기본값은 300 초 |
|    | health_check   | 헬스체크를 통해서 어플리케이션과 정상적으로 연결되어있는지 확인하는 설정이다. 헬스체크가 실패하면 새로 등록하려 한다.  |
|    | healthy_threshold   | 정상 여부를 체크하기 위한 연속 성공 횟수. 기본값은 3회 |
|    | interval   | 각 헬스체크를 시도하는 간격. 기본값은 30초  |
|    | port   | 대상 상태 확인을 위해 사용되는 포트로, 연결된 대상그룹과 동일한 경우 traffic-port, 또는 숫자로 표기  |
|    | path   | 헬스체크 관련 경로 |
|    | protocol   |  로드밸런서가 사용하는 프로토콜로 HTTP, TCP 중 하나이다.  |
|    | unhealthy_threshold   | 비정상 여부를 확인하는 연속 실패 횟수. 기본값은 3회  |
|    | matcher   |  성공적인 응답을 내려줄 때 확인 하는 코드. HTTP 또는 gRPC 코드  |
|    | timeout   |  대상으로 부터 해당 값에 시간동안 응답이 없는 경우 타임아웃으로 처리  |

2024-05-13 23:44 UTC, youngjun0627 requested changes
수고하셨습니다

2024-05-13 23:44 UTC, youngjun0627 commented on infra/aws/prod/asg.tf
> +resource "aws_instance" "algoSolved-ec2" {
ec2 는 왜 추가하신거에요?

2024-05-13 23:44 UTC, youngjun0627 commented on infra/aws/prod/asg.tf
>      propagate_at_launch = true
autoscaling group 에 [target_group_arns](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#target_group_arns) 는 혹시 보셨을까요?

2024-05-13 23:44 UTC, youngjun0627 commented on infra/aws/prod/elb.tf
> +resource "aws_lb_target_group_attachment" "algosolved-tg-attachment" {
asg 에 target_group_arns 추가하면 attachment 필요없을거에요.

ref: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#target_group_arns

NOTE on Auto Scaling Groups, Attachments and Traffic Source Attachments:
Terraform provides standalone [Attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_attachment) (for attaching Classic Load Balancers and Application Load Balancer, Gateway Load Balancer, or Network Load Balancer target groups) and [Traffic Source Attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_traffic_source_attachment) (for attaching Load Balancers and VPC Lattice target groups) resources and an Auto Scaling Group resource with load_balancers, target_group_arns and traffic_source attributes. Do not use the same traffic source in more than one of these resources. Doing so will cause a conflict of attachments. A [lifecycle configuration block](https://www.terraform.io/docs/configuration/meta-arguments/lifecycle.html) can be used to suppress differences if necessary.

2024-05-13 23:44 UTC, youngjun0627 commented on .github/workflows/TERRAFORM-PLAN.yml
> +      if: ${{ steps.check-file.outputs.exist == 'true' }}
여기 들여쓰기 안되어 있는거 같아요

2024-05-15 11:59 UTC, rha6780 commented on infra/aws/prod/asg.tf
> +resource "aws_instance" "algoSolved-ec2" {
aws_lb_target_group_attachment 에 연결 시키려고 추가했는데 아래 내용처럼 하면 필요 없겠군요! 아래 내용이랑 반영해두겠습니다.

2024-05-19 23:34 UTC, youngjun0627 commented on infra/aws/prod/elb.tf
> +    fixed_response {
밑에 rule 을 지우고 여기 `default_action` 에 타겟 그룹으로 forward 하도록 수정해도 좋을 거 같아요

```
  default_action {
    target_group_arn = <target group arn>
    type             = "forward"
  }
```

2024-05-19 23:35 UTC, youngjun0627 commented on infra/aws/prod/elb.tf
> +  subnets = [
오토스케일링 설정한 거 보면 a, b, c, d 모두 사용해서 여기도 동일하게 a, b, c, d 모두 들어가야되지 않을까 싶습니다

2024-05-21 15:56 UTC, rha6780 commented on infra/aws/prod/elb.tf
> +  subnets = [
동일하게 수정하였습니다. 👍

2024-05-21 23:32 UTC, youngjun0627 approved these changes
수고하셨습니다!

2024-05-23 10:37 UTC, merged