Settings ci environment
AlgoSolved/AlgoSolved pull request #9
Opened 2023-11-23 12:27 UTC by mmmtobezip

## 작업 내용
- Github Actions를 이용한 FE/BE CI 구축
- FE
  - Prettier, ESLint, TSC 추가
  - actions/cache을 활용하여 의존성 캐싱
  - job 분리 
  - React 테스트 커버리지 추가
 - BE
  - job 분리
  - actions/cache을 활용하여 의존성 캐싱
  -  
## 이슈
- 코드 일관성 및 안정성 확보

## 체크 리스트
- 테스트하기 위해 작성한 컨트롤러(MatchController), 테스트 코드(ActionApplicationTests) 파일 테스트 필요

2023-11-27 15:05 UTC, youngjun0627 commented on .github/workflows/BE-CI.yml
> +  contents: read
요건 왜 넣으신거에요? 불필요할 거 같아요

2023-11-27 15:05 UTC, youngjun0627 commented on .github/workflows/BE-CI.yml
> +          distribution: 'zulu'
zulu 요건 뭐에요?

2023-11-27 15:05 UTC, youngjun0627 commented on .github/workflows/FE-CI.yml
> +        run: npm run coverage
endline 추가 부탁드릴게요

2023-11-27 17:01 UTC, mmmtobezip commented on .github/workflows/BE-CI.yml
> +  contents: read
깃허브에서 제공하는 Java with Gradle 기본 템플릿을 바탕으로 작성했습니다. 
특정 작업을 수행하기 위해 필요한 권한을 명시하는 옵션으로 넣어도 되겠다 싶어 삭제하지 않았는데 말씀대로 현재 저희 작업에서는 명시하지 않아도 되겠네요!

2023-11-27 17:17 UTC, mmmtobezip commented on .github/workflows/BE-CI.yml
> +          distribution: 'zulu'
자바 환경 설정하는 부분에서 다양한 배포판 중 `distribution` 파라미터로 openJDK - Zulu 선택한겁니다.  해당 옵션은 선택사항으로 특정 배포판을 사용하고 싶을 때 명시적으로 설정해주면 됩니다!

2023-11-27 17:20 UTC, mmmtobezip commented on .github/workflows/FE-CI.yml
> +        run: npm run coverage
넵, 해당 부분 수정하겠습니다.

2023-11-30 00:09 UTC, youngjun0627 requested changes
수고하셨습니다

2023-11-30 00:09 UTC, youngjun0627 commented on .github/workflows/BE-CI.yml
> +        image: postgres:10.16
저희가 사용하는 15.x 버전과 다른거같아요

2023-11-30 00:09 UTC, youngjun0627 commented on backend/src/main/resources/application-prod.properties
> +# devtools
prod 에서는 devtools  없어야될 거에요

2023-11-30 01:06 UTC, mmmtobezip commented on .github/workflows/BE-CI.yml
> +        image: postgres:10.16
버전 변경해서 다시 올리겠습니다!

2023-11-30 02:55 UTC, rha6780 approved these changes
수고하셨습니다 👍

2023-11-30 03:48 UTC, youngjun0627 approved these changes
수고하셨습니다!

2023-11-30 04:06 UTC, merged